Backendpro/Controllers/OrdersDetailController.cs
using Backendpro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twilio;
using Twilio.Rest.Api.V2010.Account;

namespace Backendpro.Controllers
{
    [Authorize]
    public class OrdersDetailController : BaseCheckController
    {
        string accSid = "ACaa0d3f4c0b6a4ca0a0689977521620c1";
        string authToken = "b79fc9d05e7b04b1af70daffd603dffa";
        string fromwatsapp = "whatsapp:+14155238886";
        private moolansEntities1 db = new moolansEntities1();
        // GET: OrdersDetail
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewOrders()
        {
            ViewBag.logintype = Session["logintype"].ToString();
            ViewBag.Start = null;
            ViewBag.End = null;
            
            List<OrderVM> final = new List<OrderVM>();
            if(Session["logintype"].ToString() == "Admin")
            {
                List<Order> lst = db.Orders.Where(x => x.Status == "New").OrderByDescending(x => x.OrderDate).ToList();
                List<Customer> customers = db.Customers.ToList();
                List<Location> locations = db.Locations.ToList();
                foreach (var ord in lst)
                {
                    OrderVM vm = new OrderVM();
                    vm.Orderid = ord.Orderid; vm.OrderSerialno = ""; vm.OrderImage = ord.Imagepath; vm.Ordertext = ord.Ordertext; vm.Status = ord.Status;
                    vm.Customerid = ord.Customerid.Value;
                    if (string.IsNullOrEmpty(vm.Ordertext))
                    {
                        vm.Isphoto = true;
                    }
                    else
                    {
                        vm.Isphoto = false;
                    }
                    if (vm.OrderImage == null)
                    {
                        vm.OrderImage = @"~/OrderFiles/defaultorderimage.jpg";
                    }
                    Customer cust = customers.Where(x => x.Customerid == vm.Customerid).FirstOrDefault();
                    if (cust != null)
                    {
                        vm.CustomerMobileno = cust.Customermobileno;
                        vm.Customername = cust.Customername;
                        if (ord.Locationid.HasValue)
                        {
                            int temploc = ord.Locationid.Value;
                            Location loc = locations.Where(x => x.Locationid == temploc).FirstOrDefault();
                            if (loc != null)
                            {
                                vm.Locationid = loc.Locationid; vm.Location = loc.Location1;
                                final.Add(vm);
                            }
                        }
                        else
                        {
                            Location loc = locations.Where(x => cust.Locationid.HasValue && x.Locationid == cust.Locationid).FirstOrDefault();
                            if (loc != null)
                            {
                                vm.Locationid = loc.Locationid; vm.Location = loc.Location1;
                                final.Add(vm);
                            }
                        }
                        
                    }
                    
                }
            }else if (Session["logintype"].ToString() == "Vendor")
            {
                int locationid = Convert.ToInt32(Session["location"].ToString());
                List<Order> lst = db.Orders.Where(x => x.Status == "New").OrderByDescending(x => x.OrderDate).ToList();
                List<Customer> customers = db.Customers.Where(x => x.Locationid.HasValue && x.Locationid.Value == locationid).ToList();
                lst = (from ls in lst
                       join cs in customers on ls.Customerid equals cs.Customerid
                       select ls).ToList();
                List < Location > locations = db.Locations.ToList();
                foreach (var ord in lst)
                {
                    OrderVM vm = new OrderVM();
                    vm.Orderid = ord.Orderid; vm.OrderSerialno = ""; vm.OrderImage = ord.Imagepath; vm.Ordertext = ord.Ordertext; vm.Status = ord.Status;
                    vm.Customerid = ord.Customerid.Value;
                    if (string.IsNullOrEmpty(vm.Ordertext))
                    {
                        vm.Isphoto = true;
                    }
                    else
                    {
                        vm.Isphoto = false;
                    }
                    if (vm.OrderImage == null)
                    {
                        vm.OrderImage = @"~/OrderFiles/defaultorderimage.jpg";
                    }
                    Customer cust = customers.Where(x => x.Customerid == vm.Customerid).FirstOrDefault();
                    if (cust != null)
                    {
                        vm.CustomerMobileno = cust.Customermobileno;
                        vm.Customername = cust.Customername;
                        if (ord.Locationid.HasValue)
                        {
                            int temploc = ord.Locationid.Value;
                            Location loc = locations.Where(x => x.Locationid == temploc).FirstOrDefault();
                            if (loc != null)
                            {
                                vm.Locationid = loc.Locationid; vm.Location = loc.Location1;
                                final.Add(vm);
                            }
                        }
                        else
                        {
                            Location loc = locations.Where(x => cust.Locationid.HasValue && x.Locationid == cust.Locationid).FirstOrDefault();
                            if (loc != null)
                            {
                                vm.Locationid = loc.Locationid; vm.Location = loc.Location1;
                                final.Add(vm);
                            }
                        }

                    }

                }
            }
            
            
            return View(final);
        }

        public ActionResult PreviousOrders()
        {
            ViewBag.logintype = Session["logintype"].ToString();
            ViewBag.Start = null;
            ViewBag.End = null;
            List<OrderVM> final = new List<OrderVM>();
            if (Session["logintype"].ToString() == "Admin")
            {
                List<Order> lst = db.Orders.Where(x => x.Status != "New").OrderByDescending(x => x.OrderDate).ToList();
                List<Customer> customers = db.Customers.ToList();
                List<Location> locations = db.Locations.ToList();
                foreach (var ord in lst)
                {
                    OrderVM vm = new OrderVM();
                    vm.Orderid = ord.Orderid; vm.OrderSerialno = ""; vm.OrderImage = ord.Imagepath; vm.Ordertext = ord.Ordertext; vm.Status = ord.Status;
                    vm.Customerid = ord.Customerid.Value;
                    if (string.IsNullOrEmpty(vm.Ordertext))
                    {
                        vm.Isphoto = true;
                    }
                    else
                    {
                        vm.Isphoto = false;
                    }
                    if (ord.Status == "Completed")
                    {
                        vm.isButtonDisabled = true;
                    }
                    if (vm.OrderImage == null)
                    {
                        vm.OrderImage = @"~/OrderFiles/defaultorderimage.jpg";
                    }
                    Customer cust = customers.Where(x => x.Customerid == vm.Customerid).FirstOrDefault();
                    if (cust != null)
                    {
                        vm.CustomerMobileno = cust.Customermobileno;
                        vm.Customername = cust.Customername;
                        if (ord.Locationid.HasValue)
                        {
                            int temploc = ord.Locationid.Value;
                            Location loc = locations.Where(x => x.Locationid == temploc).FirstOrDefault();
                            if (loc != null)
                            {
                                vm.Locationid = loc.Locationid; vm.Location = loc.Location1;
                                final.Add(vm);
                            }
                        }
                        else
                        {
                            Location loc = locations.Where(x => cust.Locationid.HasValue && x.Locationid == cust.Locationid).FirstOrDefault();
                            if (loc != null)
                            {
                                vm.Locationid = loc.Locationid; vm.Location = loc.Location1;
                                final.Add(vm);
                            }
                        }

                    }

                }
            }
            else if (Session["logintype"].ToString() == "Vendor")
            {
                List<Order> lst = db.Orders.Where(x => x.Status != "New").OrderByDescending(x => x.OrderDate).ToList();
                int locationid = Convert.ToInt32(Session["location"].ToString());
                List<Customer> customers = db.Customers.Where(x => x.Locationid.HasValue && x.Locationid == locationid).ToList();
                lst = (from ls in lst
                       join cs in customers on ls.Customerid equals cs.Customerid
                       select ls).ToList();
                List<Location> locations = db.Locations.ToList();
                foreach (var ord in lst)
                {
                    OrderVM vm = new OrderVM();
                    vm.Orderid = ord.Orderid; vm.OrderSerialno = ""; vm.OrderImage = ord.Imagepath; vm.Ordertext = ord.Ordertext; vm.Status = ord.Status;
                    vm.Customerid = ord.Customerid.Value;
                    if (string.IsNullOrEmpty(vm.Ordertext))

Backendpro/Views/OrdersDetail/NewOrders.cshtml
@model IEnumerable<Backendpro.Models.OrderVM>
@{
    ViewBag.Title = "NewOrders";
    if (ViewBag.logintype == "Admin")
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    if (ViewBag.logintype == "Vendor")
    {
        Layout = "~/Views/Shared/_LayoutVendor.cshtml";
    }

    WebGrid webGrid = new WebGrid(Model);
}

<h4>New Orders</h4>

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .Grid {
        border: 1px solid #ccc;
        border-collapse: collapse;
    }

        .Grid th {
            background-color: #F7F7F7;
            font-weight: bold;
        }

        .Grid th, .Grid td {
            padding: 5px;
            border: 1px solid #ccc;
        }

        .Grid, .Grid table td {
            border: 0px solid #ccc;
        }

            .Grid th a, .Grid th a:visited {
                color: #333;
            }
</style>





@using (Html.BeginForm("FilterdateNew", "OrdersDetail", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-3">
            <input type="datetime" name="startdate" placeholder="CHOOSE START DATE" value="@ViewBag.Start" class="form-control" />
        </div>
        <div class="col-md-3">
            <input type="datetime" name="enddate" placeholder="CHOOSE END DATE" value="@ViewBag.End" class="form-control" />
        </div>
        <div class="col-md-3">
            <input type="submit" class="btn btn-primary" value="Search" />
        </div>
    </div>
}



@webGrid.GetHtml(
    tableStyle: "table table-bordered table-striped mr",
    rowStyle: "gridrow",
    alternatingRowStyle: "gridalt",
        htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        columns: webGrid.Columns(
                 webGrid.Column("Customername", "Customer Name"),
                 webGrid.Column("CustomerMobileno", "Customer Mobile"),
                 webGrid.Column(header: "Order Text", format: @<text>@{


                                    if (item.Isphoto == false)
                                    {
                            @Html.Raw("<text><input type='button' value='View Order Text' onclick='seeText(" + item.Orderid + ")'  /></text>");
                                    }
                                    else
                                    {
                            @Html.Label("No Text");
                                    }

                }</text>),
webGrid.Column(header: "Order Snapshot", format: @<text>@{


                                if (item.Isphoto == true)
                                {
                        @Html.Raw("<text><input type='button' value='View Order Snapshot' onclick='seeImage(" + item.Orderid + ")'  /></text>");
                                }
                                else
                                {
                        @Html.Label("No Image");
                                }

}</text>),

webGrid.Column("Location", "Location"),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Accept", "AcceptOrder", "OrdersDetail",
new
{
Orderid = item.Orderid
}, null)),
webGrid.Column(columnName: "", format: (item) => Html.ActionLink("Reject", "RejectOrder", "OrdersDetail",
new { Orderid = item.Orderid }, null))

))




<div id="openpopup" style="display:none;"></div>
<div id="openpopuptext" style="display:none;"></div>

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true
            });

        });


        function seeImage(orderid) {
            var x = $('#openpopup');
            x.load("/OrdersDetail/SeeOrderImage?orderid=" + orderid, function () {
                x.dialog({
                    show: {
                        effect: "blind",
                        duration: 1000
                    },
                    hide: {
                        effect: "explode",
                        duration: 1000
                    },
                    modal: true,
                    width: 550,
                    height: 550,
                    title: "Order Snapshot",
                    resizable: false
                });
            });
        }

        function seeText(orderid) {
            var x = $('#openpopuptext');
            x.load("/OrdersDetail/SeeOrderDetails?orderid=" + orderid, function () {
                x.dialog({
                    show: {
                        effect: "blind",
                        duration: 1000
                    },
                    hide: {
                        effect: "explode",
                        duration: 1000
                    },
                    modal: true,
                    width: 550,
                    height: 550,
                    title: "Order Text",
                    resizable: false
                });
            });
        }
    </script>
}

Backendpro/Views/OrdersDetail/PreviousOrders.cshtml
@model IEnumerable<Backendpro.Models.OrderVM>
@{
    ViewBag.Title = "PreviousOrders";
    if (ViewBag.logintype == "Admin")
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    if (ViewBag.logintype == "Vendor")
    {
        Layout = "~/Views/Shared/_LayoutVendor.cshtml";
    }
    WebGrid webGrid = new WebGrid(Model);
}

<h4>Previous Orders</h4>

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .Grid {
        border: 1px solid #ccc;
        border-collapse: collapse;
    }

        .Grid th {
            background-color: #F7F7F7;
            font-weight: bold;
        }

        .Grid th, .Grid td {
            padding: 5px;
            border: 1px solid #ccc;
        }

        .Grid, .Grid table td {
            border: 0px solid #ccc;
        }

            .Grid th a, .Grid th a:visited {
                color: #333;
            }
</style>





@using (Html.BeginForm("FilterdatePre", "OrdersDetail", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-3">
            <input type="datetime" name="startdate" placeholder="CHOOSE START DATE" value="@ViewBag.Start" class="form-control" />
        </div>
        <div class="col-md-3">
            <input type="datetime" name="enddate" placeholder="CHOOSE END DATE" value="@ViewBag.End" class="form-control" />
        </div>
        <div class="col-md-3">
            <input type="submit" class="btn btn-primary" value="Search" />
        </div>
    </div>
}



@webGrid.GetHtml(
    tableStyle: "table table-bordered table-striped mr",
    rowStyle: "gridrow",
    alternatingRowStyle: "gridalt",
        htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        columns: webGrid.Columns(
                 webGrid.Column("Customername", "Customer Name"),
                 webGrid.Column("CustomerMobileno", "Customer Mobile"),
                 webGrid.Column("Ordertext", "Orders"),
                 webGrid.Column("Location", "Location"),

                 webGrid.Column(format: (item) =>
                 {
                     if (item.isButtonDisabled == false)
                     {
                         return Html.ActionLink("Dispatch", "CompleteOrder", "OrdersDetail", new { Orderid = item.Orderid }, null);
                     }
                     else
                     {
                         return Html.Label("Completed");
                     }
                 }




                 )

))

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true
            });

        });



    </script>
}

Backendpro/Views/OrdersDetail/SeeOrderDetails.cshtml
@model Backendpro.Models.OrderVM

<div style="width:500px; height: 500px;">
   <p> @Model.Ordertext</p>




</div>

Backendpro/Views/OrdersDetail/SeeOrderImage.cshtml
@model Backendpro.Models.OrderVM

    <div style="width:500px; height: 500px;">
        <img src="@Url.Content(Model.OrderImage)" width="400" height="400" />




    </div>